### ISSUE TITLE
the server side extdb was not loaded into the engine repor this to the server admin

### ISSUE THREAD

**Issue by PostGresSQL** [SteezCram/extDB3#10]
Cant seem to fix this issue 

![Screenshot_1](https://user-images.githubusercontent.com/22871127/126479493-ace52769-9c32-4bb4-89b7-3be7bc92c5dd.png)

**Comment by SteezCram** [comment]
Hello, did you have other logs? Plus when searching it seems about an old version of extDB, not extDB3.

**Comment by PostGresSQL** [comment]
> Hello, did you have other logs? Plus when searching it seems about an old version of extDB, not extDB3.

This is my rtp log 
https://drive.google.com/file/d/1K_pUvu6Jo4tdmXz2wlHBJtV4oHaVfYZC/view?usp=sharing
I have been debugging a bit myself, thanks for helping me with this issue.

I have used extdb , extdb2 , and extdb3 , all giving the same issues when joining the game it gives that message.

**Comment by PostGresSQL** [comment]
> Hello, did you have other logs? Plus when searching it seems about an old version of extDB, not extDB3.

I fixed the issue , i was running redis on the background which prevented the connection , not sure how or why, turned it off and worked fine after.

**Comment by SteezCram** [comment]
Ok, clearly I don't see the link between Redis and extDB, maybe Redis was on the same port as MariaDB or MySQL.

Since you resolved this issue, I close the issue.

**Comment by SteezCram** [comment]
Ok, clearly I don't see the link between Redis and extDB, maybe Redis was on the same port as MariaDB or MySQL.

Since you resolved this issue, I close the issue.
