### ISSUE TITLE
Extdb3 saving things but kills

### ISSUE THREAD

**Issue by Guerinnii** [SteezCram/extDB3#13]
I was able to setup extdb3 on my server, It seemed that everything worked correctly, when a player joined the server a new column was created with the player's data. but it seems that the kills are bugged, the other day a player had approximately 80 and when he left the server the number was not updated in the database (it is an example of many) Others simply remain at 0. I hope someone can help me

**Comment by Guerinnii** [comment]
This is scores in game: https://ibb.co/kXw4VMK

This is scores at database: https://ibb.co/F0rKfrB

So, only ''points'' works properly.

**Comment by SteezCram** [comment]
Hello, I don't think your problem is concerned with extDB but rather with some of your scripts. First, check for errors in them.
