### ISSUE TITLE
64 bit Linux?

### ISSUE THREAD

**Issue by klovok** [SteezCram/extDB3#2]
Is it possible to use this with new 64bit Arma 3 Linux Server?

**Comment by SteezCram** [comment]
Hello,

You have to compile the source for 64 bits.

**Comment by elstp** [comment]
Do you have time to upload an extdb_x64.so file?
Thank you very much!

**Comment by klovok** [comment]
Going to close this issue, as it is continued in [Issue #3 ](https://github.com/SteezCram/extDB3/issues/3).
Very much appreciate your time on this Steez!
