### ISSUE TITLE
extDB3: Error Invalid Format

### ISSUE THREAD

**Issue by tomas1207** [SteezCram/extDB3#5]
Hi guys i know you arent the onwer of the mod but how i can resolve this erro.
extDB3: Error Invalid Format:
And 
Unknow Protocol

**Comment by SteezCram** [comment]
Hello, post all your logs, else nobody can help you.

**Comment by tomas1207** [comment]
Logs:

```
extDB3: https://bitbucket.org/torndeco/extdb3/wiki/Home
extDB3: Version: 1.033
extDB3: Windows Version
Message: All development for extDB3 is done on a Linux Dedicated Server
Message: If you would like to Donate to extDB3 Development
Message: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Message: Also leave a message if there is any particular feature you would like to see added.
Message: Thanks for all the people that have donated.
Message: Torndeco: 18/05/15

Message: This version was modified and include some improvement
Message: The lib was recompiled using new version of TBBMalloc, Boost and MariaDB connector
Message: The worker threads limitation was removed
Message: Steez: 30/10/2020


extDB3: Found extdb3-conf.ini
extDB3: Detected 8 Cores, Setting up 6 Worker Threads
extDB3: Detected 8 Cores, Setting up 8 Worker Threads
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...


[14:37:51:411431 +00:00] [Thread 11284] extDB3: Error Unknown Protocol: sql  Input String: 2:sql:SELECT * FROM shootfired
```

**Comment by SteezCram** [comment]
Maybe it's your altislife or something wrong with the installation.

The new version works since I tested it on a server before. That's the only things I can say.

**Comment by Tally-1** [comment]
It could be a server issue as well, I when I run extDB3 on my own pc it connects perfectly with Mysql However on my rented server it does not. It is a virtual machine, and I am trying to resolve the issue now. If I get a solution I'll post here

**Comment by Tally-1** [comment]
Ok found the solution to my server issue, and after reading trough this thread I see that it is not that related to the issue.

Anyway, the problem was that the server-machine did not have Python installed
