### ISSUE TITLE
Can't find any tutorial

### ISSUE THREAD

**Issue by irkanot** [SteezCram/extDB3#6]
even if i search everywhere on google i can't find any single tutorial for how to use extDB3

**Comment by SteezCram** [comment]
Hello, did you check the wiki: https://github.com/SteezCram/extDB3/wiki ?

**Comment by irkanot** [comment]
Yes, but i can't find any example about extDB3 usage with arma 3 scripts

**Comment by SteezCram** [comment]
You have an example in the Tonic mission to make some request, but everything is written in the wiki, it's a theoric but it's how it works.

**Comment by SteezCram** [comment]
No response, I close the issue
